#!/bin/bash

### ---------------------------------------------------------------
# simple commit message hook to verify the commit message **starts** in correct format
### ---------------------------------------------------------------
# Use .githooks folder instead of .git/hooks to use the hooks in this Project
#
#    git config core.hooksPath ./.githooks
#
# Make sure the file is executable
#
#    chmod 744 ./.githooks/pre-commit
#
### ---------------------------------------------------------------

CHANGED_PYTHON_FILES=$(git diff --cached --name-only --diff-filter=ACM  -- . ':!migrations' | grep -E '\.py$')

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

FORMAT_CHECK_SCRIPT="../setup/dev/docker/pre-commit/pre-commit-check.sh"
FORMAT_CHECK_COMPOSE="../setup/dev/docker/pre-commit/docker-compose.yml"

# run global pre commit check in the ./setup/dev/docker/pre-commit folder, and pass the commit information as arguments
$FORMAT_CHECK_SCRIPT $FORMAT_CHECK_COMPOSE pipeline "$BRANCH_NAME" "$CHANGED_PYTHON_FILES" 

if [ $? -ne 0 ]; then
    echo "pre-commit fail. Please fix the errors and try again."
    exit 1
fi

exit 0