### Example request to create relation basic nn
POST http://localhost/pipeline/train/relation?
   model_type=basic_nn
   &name=CustomModel1
   &model_size=medium
   &enable_evaluation=True
Content-Type: application/json

< ./train_nn_test_input.json
